development:
  adapter: postgresql
  host: localhost
  database: Yoshi_API_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  host: localhost
  database: Yoshi_API_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  database: Yoshi_API_production
  pool: 5
  timeout: 5000
